language: minimal
sudo: required
services:
- docker
env: 
script:
- "./wget_latest.sh"
deploy:
  provider: releases
  api_key:
    secure: "RtyYgQeAg3UScG+fEwFs0V4hD7+3w8qMj1MA2B4hLNFg+cUKW2OVFrGTsMNo/YAZyxmvrXTA+oeyToZmGLOSFJGpqpIcJGa3a5P9bp3Zmu8l3xCdlgLEvPnW4ooDtCfAz+dFZW46qiHN7u2HHL9p0qE1XxhDFAYgnzr1zby9AfcE7vd1kar9O3G9Msc8waqLTtVP7Bc53hob4ywfc5oVVkEwFdBffLfoTjJdBRIBPl4JmIY0NugYVrnb4zfxX20LkWacnSoBWyPMyrDMwHjQUyVvRnULf9gmpFY5Gmh7dfs3A7J6jxezBzdsHrzGsAlwL1dOp9jMVIAa53liJ2417Qy5Z/5VcEJcYlc/EdvDuyMl5MTXtDfy5j3VtBUeR1I5h3juBIkCA/wlZAUYpJxrAvh4akU5gtJf8wQCAB9fC6xLZLnWLULYy9Jig1pXeWOXCvLVC9eOOi5+PuygAVeddzLrLiIW5UTflwXeAVZM4JQywMGv5r5nRSbqFCQEQz/Z4cTYD/OdCYe7HBJMjoW5LYjv9XyYYL+STFWj5zJuD1o19tNHPO35mbnANS4P1szrUrOw7IEhg1VdP+PCSa9LAj4rTM5jlHeb4umgWFliTLOoxpV9uwD3KTiajhLytQgWMEiy/d7Xs/xNVcY7Ct3kucaR5Jb45otc9BGY85LtuJQ="
  file: artifacts/bundles/opsMarina_Darwin_x86_64.tar.gz
  on:
    repo: slmingol/opsMarina
