language: minimal
sudo: required
services:
- docker
env:
script:
- "./wget_latest.sh"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - artifacts/bundles/opsMarina_Darwin_x86_64.tar.gz
    - artifacts/bundles/opsMarina_Linux_x86_64.tar.gz
  skip_cleanup: true
  on:
    tags: true
