language: minimal
sudo: required
services:
- docker
env: 
script:
- "./wget_latest.sh"
deploy:
  provider: releases
  api_key:
    secure: "l/XWWEHeC/Ec3voW3VHAEyUfFlSkFzj1cIjEJFKn4nbSCahF6dKMonsIQVdL8D+0Ray2tpXMnGma++d2YC+ulTnWOeyCxM1drGX1U/6qbJJoharctgwDpVPlO/KbniDceUj0DB37vszMxIDehBr76QJMHYZLV8I6i6TZn0TnOKcJM/mV9lTtjR6y1woa1pXfDFvidvLQu1V0DHOpTNkZ2vy5XoFJU3CdoRFmBHS1DUQI63MGfegCwfvFYGLEPmOkSXvPpSGkWWANvHjnbwwH3J7vZGxRC7jRruGlTMCRWg2cZyvh6MGRIFP5FBMmxMkLRnINCslziekYEcneSHINDx2l4jeyRGNgqVKGF9DmQQIJqDc7evC2qTj2k98GIv4b4Dh73bWFFpJ6CJIegyUoY3FS8jswgeBOcFUdNWJO+kwtWI0JzLiNpscpQGup2gchEr/sacPOZXR/hB0SwEjemSUKgmvLitZx6QOic+IY88AaJN3S73aEHQmdP7j3GogRDSQAXSGOTv6Uwenf5s5ma6K4JpXRx1xTbh89WTytzJ4za2DEbbv1Q/+U1Mc1egeFMqBx0RQx6SgLLm+aYks3FOhurd/zz5xJadH82HFcFb7ZiX8iEE6M9eY3xe6HequyuKnzxfvUmI+GvnK52mI3XFJLB+yR1efA8r+sTWTy5vY="
  file: artifacts/bundles/opsMarina_Darwin_x86_64.tar.gz
  on:
    repo: slmingol/opsMarina
